apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: payments-ms
  name: payments-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: payments-ms
    spec:
      containers:
        - image: northamerica-south1-docker.pkg.dev/microservices-dev-452315/image-registry/payments-ms
          name: payments-ms
          env:
            - name: PORT
              value: "3010"
            - name: NATS_SERVERS
              value: "nats://nats"
            - name: SUCCESS_URL
              value: "http://localhost:3010/api/payments/success"
            - name: CANCEL_URL
              value: "http://localhost:3010/api/payments/cancel"

            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: payment-secrets
                  key: STRIPE_SECRET_KEY

            - name: STRIPE_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: payment-secrets
                  key: STRIPE_WEBHOOK_SECRET
          resources: {}
status: {}
